CONCD-1007 Bootstrap tweaks (#2640)
* CONCD-1007 Additional bootstrap fixes (#2607)

* CONCD-1007 the page status does not seem to 'stick' without refreshing the page.

* CONCD-1007 when you accept, button options (Edit/ Accept) should change

* CONCD-1007 I don't think we actually need to close the modal, since we're just going to reload the page anyways

* CONCD-1007 transcription status completely disappears from the page when undoing/ redoing

* CONCD-1007 Reset all button should have rounded corners

* CONCD-1007 Campaign tips carousel is the bright blue - should be muted

* CONCD-1007 OCR buttons should be aligned with right edge of viewers

* CONCD-1007 After clicking Edit, have to reload page to see OCR options

* CONCD-1007 Gray box around tag X

* CONCD-1007 Slider is bright blue - should be muted

* CONCD-1007 Add button doesn't re-highlight as available after 1 tag has been added

* CONCD-1007 inconsistent styling for newly added tags

* CONCD-1007 trying to restore the homepage carousel to its original size

* CONCD-1007 Arrows are still hard to see

* CONCD-1007 Text box and arrows are cut off when browser is narrowed

* CONCD-1007 missing files (#2621)

* CONCD-1007 Still a few issues (#2626)

* CONCD-1007 in a larger browser window, fill the entire screen

* CONCD-1007 Invert filter slider should be centered

* CONCD-1007 Invert filter slider should be on the same vertical line as the label text

* CONCD-1007 trying to fix another issue where the status goes missing

* CONCD-1007 fixing a bug in the previous commit

* CONCD-1007 trying to revert our carousel dimensions to what it was (before the bootstrap upgrade)

* CONCD-1007 TypeError: element.attr is not a functions (#2627)

* CONCD-1007 Invert filter slider should be centered between On and Off (currently much closer to Off) (#2632)

* Update stage-hotfix-rel-deploy.yml

remove pipenv run for hot fix version number generation

* CONCD-1007  (#2639)

* CONCD-1007 trying to fix an issue where the page status still disappears (after OCR is generated)

* CONCD-1007 need to unhide the element after it's been hidden

* CONCD-1007 OCR module slide 1's X has to be clicked twice to close the popup

* CONCD-1007 trying to compensate for the campaign titles appearing to be slightly indented on the campaign page (/campaigns-topics/)

---------

Co-authored-by: Jennifer Kuenning <72825410+jkueloc@users.noreply.github.com>